apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-todolist
  name: my-todolist-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 8000
  selector:
    app: my-todolist