GET http://localhost:8000/todo
Accept: application/json

###

GET http://localhost:8000/todo/1
Accept: application/json

###

POST http://localhost:8000/todo
Content-Type: application/json

{
  "newtodo": "value1"
}

###

PUT http://localhost:8000/todo/0
Content-Type: application/json

{
  "updatetodo": "value100"
}


###